version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      PMA_HOST: db

  wordpress:
    depends_on:
      - db
    image: wordpress:php7.0
    ports:
      - '80:80'
    environment:
      DB_HOST: db
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_NAME: wordpress
      MULTISITE_DOMAIN: carnegieinternational.test
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USER: wordpress
      MAIL_PASS: wordpress
      MAIL_SMTPAUTH: 0
      MAIL_SECURITY: tls
      S3_UPLOADS_USE_LOCAL: 1
      S3_UPLOADS_DISABLE_REPLACE_UPLOAD_URL: 1
      WP_ENV: development
    volumes:
      - .:/var/www/html/wp-content/themes/ci2018
      - ../../plugins:/var/www/html/wp-content/plugins
      - ../../uploads:/var/www/html/wp-content/uploads
      - ../../../wp-config.php:/var/www/html/wp-config.php

  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
      - '1025:1025'

volumes:
  ? db_data
