---
server:
    install: '1'
    packages: [vim, git, fail2ban, imagemagick]
    timezone: America/New_York
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: ci2018, ip: 192.168.50.6, memory: '1024', sharedfolder: ./, syncType: nfs }
nginx:
    install: '1'
    docroot: /vagrant
    servername: ci2018.dev
mysql:
    install: '1'
    root_password: '123'
    database: ci2018
    user: user
    password: password
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-mysql, php5-gd]
